import { ServiceData } from '@utils/interfaces';

import { uniqueSuffix } from './shared-data';

export function normalizeServiceTitle(value?: string): string {
  return (value ?? '')
    .normalize('NFKD')
    .replace(/[^a-zA-Z0-9]/g, '')
    .trim();
}

export function createServiceName(prefix: string): string {
  const normalizedPrefix = normalizeServiceTitle(prefix).toLowerCase();
  return normalizeServiceTitle(`${normalizedPrefix}${uniqueSuffix()}`);
}

export function createUpdatedServiceName(baseName: string): string {
  return normalizeServiceTitle(`${baseName}updated`);
}

export function createValidServiceData(overrides: Partial<ServiceData> = {}): ServiceData {
  const data: ServiceData = {
    title: createServiceName('autotestservice'),
    description: 'autogenerated test service',
    ...overrides,
  };

  const normalizedTitle = normalizeServiceTitle(data.title);

  if (!normalizedTitle) {
    throw new Error('Service title is required when creating service test data');
  }

  return { ...data, title: normalizedTitle };
}
