function normalizeServiceTitle(value) {
  const normalized = String(value ?? '')
    .normalize('NFKD')
    .replace(/[^a-zA-Z0-9]/g, '')
    .trim();

  return normalized;
}

function createServiceName(prefix = 'autotestservice') {
  const normalizedPrefix = normalizeServiceTitle(prefix).toLowerCase() || 'autotestservice';
  const stamp = new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14);
  const random = Math.random().toString(36).replace(/[^a-z0-9]/g, '').slice(0, 6);
  return normalizeServiceTitle(`${normalizedPrefix}${stamp}${random}`);
}

function createUpdatedServiceName(baseName) {
  return normalizeServiceTitle(`${baseName}updated`);
}

function createValidServiceData(overrides = {}) {
  const data = {
    title: createServiceName('autotestservice'),
    description: 'autogenerated test service',
    ...overrides,
  };

  const normalizedTitle = normalizeServiceTitle(data.title);

  if (!normalizedTitle) {
    throw new Error('Service title is required when creating service test data');
  }

  data.title = normalizedTitle;
  return data;
}

module.exports = {
  normalizeServiceTitle,
  createServiceName,
  createUpdatedServiceName,
  createValidServiceData,
};
