import { ServiceData } from '@utils/interfaces';

export function normalizeServiceTitle(value?: string): string {
  return (value ?? '')
    .normalize('NFKD')
    .replace(/[^a-zA-Z0-9]/g, '')
    .trim();
}

export function createServiceName(prefix: string): string {
  const normalizedPrefix = normalizeServiceTitle(prefix).toLowerCase();
  const stamp = new Date()
    .toISOString()
    .replace(/[-:.TZ]/g, '')
    .slice(0, 14);
  const random = Math.random()
    .toString(36)
    .replace(/[^a-z0-9]/g, '')
    .slice(0, 6);
  return normalizeServiceTitle(`${normalizedPrefix}${stamp}${random}`);
}

export function createUpdatedServiceName(baseName: string): string {
  return normalizeServiceTitle(`${baseName}updated`);
}

export function createValidServiceData(overrides: Partial<ServiceData> = {}): ServiceData {
  const data: ServiceData = {
    title: createServiceName('autotestservice'),
    description: 'autogenerated test service',
    ...overrides,
  };

  const normalizedTitle = normalizeServiceTitle(data.title);

  if (!normalizedTitle) {
    throw new Error('Service title is required when creating service test data');
  }

  return { ...data, title: normalizedTitle };
}
